languages = \
{
	"english": {
		"self": "english",
		"": "",
		"Last Name": "Last Name",
		"First Name": "First Name",
		"Chinese Name": "Chinese Name",
		"School Location": "School Location",
		"Barcode": "Barcode",
		"Old Student ID": "Old Teacher ID",
		"Date of Birth": "Date of Birth",
		"Age": "Age",
		"Gender": "Gender",
		"Parent Name": "Parent Name",
		"Home Phone": "Home Phone",
		"Cell Phone": "Cell Phone",
		"Cell Phone 2": "Cell Phone 2",
		"Pick up Person": "Pick up Person",
		"Address": "Address",
		"State": "State",
		"City": "City",
		"Zipcode": "Zipcode",
		"Weekday/Weekend": "Weekday/Weekend",
		"Tuition Paid Day": "Tuition Paid Day",
		"Payment Method": "Payment Method",
		"Tuition Pay Amount": "Total Amount",
		"E-mail": "E-mail",
		"Service Type": "Service Type",
		"Classes Awarded": "Classes Awarded",
		"Classes Remaining": "Classes Remaining",
		"Date": "Date",
		"Time": "Time",
		"Check-In Time": "Check-In Time",
		"Check-Out Time": "Check-Out Time",
		"Start Time": "Start Time",
		"Class Time": "Class Time",
		"How did you hear about the school?": "How did you hear about this school?",
		"Notes": "Notes",
		"No student": "Teacher was not found! Please try again!",
		"Confirm Teacher Addition": "Are you sure you would like to add this teacher to the Database?",
		"Confirm Save Teacher Data": "Are you sure you would like to save this teacher's information to the Database?",
		"Confirm Overwrite Teacher": "Teacher with this barcode exists in the database Adding this teacher will overwrite the existing student. Overwrite current student?",
		"Teacher has been added to the database": "Teacher has been added to the database",
		"Confirm Check-in Teacher": "Check in the teacher?",
		"Check out prompt": "Check out the teacher?",
		"No classes": "Teacher does not have any more classes!",
		"Con print": "You sure to print file?",
		"Overwrite Checkout": "Teacher checked-out today. Overwrite current check-out?",
		"Overwrite Check-In": "Overwrite Check-in",
		"No Check-in today": "Teacher has not checked-in today",
		"Confirm late check-in": "Do you want to count this Check-In as 9:15AM?",
		"ok": "    Ok    ",
		"yes": "    Yes    ",
		"no": "    No    ",
		"impdb": "Import Database",
		"expdb": "Export Database",
		"impxls": "Import from Excel",
		"impt": "Import Time Data",
		"imptxls": "Import Time Data from Excel",
		"expxls": "Export Database",
		"curfile": "Current Database File",
		"browse": "Browse",
		"browsephoto": "Select Picture",
		"filepath": "File Path",
		"Back": "Back",
		"Next": "Next",
		"saveto": "Save To",
		"Save": "Save",
		"choosedb": "Choose Database",
		"changelanguage": "中文",
		"changelanguage_alt": "中文",
		"awardclass": "Award Classes",
		"awardoneclass": "Single (+1)",
		"awardaddclass": "Award Additional Classes",
		"addstudent": "Add Teacher to Database",
		"Add Students": "Add Teachers", #students* for buttons
		"Scan Students": "Check-in Teacher",
		"Scan Out Teacher": "Check-Out Teacher",
		"Student Database": "Teacher Database",
		"Tools": "Database Management",
		"Back to Main Menu": "Back to Main Menu",
		"Exit": "Exit",
		"Search": "Search",
		"cinstudent": "Check-In Teacher",
		"Search By": "Search By",
		"savestudent": "Save Teacher",
		"Database succesfully updated!": "Database succesfully updated!",
		"File could not be imported": "File could not be imported",
		"Cancel": "Cancel",
		"Please choose a file": "Please choose a file",
		"spec": "",
		"Classes remaining for this teacher": "Classes remaining for this teacher",
		"gold60": "Gold (+60)",
		"basic15": "Basic (+15)",
		"Return to Main Window": "Return to main window without saving?",
		"Scan": "Scan",
		"Manual": "Manual",
		"close": "Close",
		"Amount Owed": "Amount Owed",
		">> Next 30 >>": "Next",
		"<< Previous 30 <<": "Previous",
		">>> Last Page >>>": "Last Page",
		"Import succesful": "Import succesful",
		"Students imported: ": "Teacher imported: ",
		"Attendance data imported: ": "Attendance imported: ",
		"Student information": "Teacher information",
		"Address information": "Address",
		"Contact information": "Contact",
		"Payment information": "Payment",
		"Class time": "Class time",
		"Renew classes": "Renew classes",
		"Number of classes": "Classes to add",
		"Membership Expired": "Membership Expired",
		"Card Printed": "Card Printed",
		"Already Paid": "Already Paid",
		"Phone Number": "Phone Number",
		"RYB Student Management" : "RYB Teacher Management",
		"print report": "Print Report",
		"sdate": "Search Date",
		"Select Folder": "Select Folder",
		"salrep": "Salary Report",
		"print to file": "Make Report",
		"today's date": "Today's date",
		"last payment": "Last Payment",
		"dollar per hour": "Dollars/hour",
		"Hour": "Hour",
		"Minute": "Minute",
		"AM/PM": "AM/PM",
		"Print All": "Print All",
		"Confirm Time": "Confirm Time",
		"Confirm": "Confirm",
		"25s": " 25s",
		"50s": " 50s",
		"100s": " 100s",
		"set": "Set",
		"reset": "Reset",
		"resetcheckin": "Reset Check-In",
		"Confirm Reset": "Confirm Reset",
		"Early Check-ins have been reset": "Early Check-ins have been reset",
		"Yes, use current time": "Yes, use current time",
		"Yes, enter time": "Yes, enter time",
		"Brooklyn": "Brooklyn",
		"Chinatown": "Chinatown",
		"Elmhurst": "Elmhurst",
		"Flushing": "Flushing",
		"Choose School": "Choose School",
		"Print Successful": "Print Successful",
		"Early Check-in": "Early Check-in",
		"max hours": "Maximum Hours",
		"Choose PW File": "Choose PW File",
		"Create PW File": "Create PW File",
		"Create new Database": "Create new Database",
		"Convert to Encrypted DB": "Convert to Encrypted DB",
		"no_pw_set_pw": "Password must be reset.Please enter the old password followed by the new password",
		"Enter Password": "Enter Password",
		"Reset DB Manager PW": "Reset DB Manager PW",
		"confirmed reset": "Password has been reset!",
		"wrong password try again": "You have entered the wrong password, try again!",
		"Choose Maker File": "Choose Maker File",
		"Create new Markerfile": "Create new Markerfile",
		"Database Backup Successful": "Database Backup Successful",
		"Student Information": "Teacher Information",
		"Attendance Table": "Sign-in Table",
		"Manual Entry": "Manual Entry",
		"Save Attendance": "Save Attendance",
		"Check-in": "到达时间",
		"Check-out": "Check-out",
		"Check-in date": "Check-in date",
		"School": "School",
		"Invalid Date": "Invalid Date",
		"Return": "Return",
		"Teacher Print Successful": "Teacher Print Successful",
		"Check-Out Cannot be earlier than Check-In": "Check-Out Cannot be earlier than Check-In",
		"No Check-In on that Date": "No Check-In on that Date",
		"Cannot Check-In a future time": "Cannot Check-In a future time",
		"Password File": "Password File",
		"Preview": "Preview",
		"Output File": "Output File",
		"Source Excel": "Source Excel",
		"Invalid File Type": "Invalid File Type",
		"Print Simple Report": "Print Simple Report"
		},

	"chinese": {
		"self": "chinese",
		"First Name": "  名字  ",
		"Last Name": "    姓    ",
		"Chinese Name": "  中文名字  ",
		"School Location": "学校位置",
		"Barcode": "条码号",
		"Old Student ID": "旧学号",
		"Date of Birth": "生日",
		"Age": "年龄",
		"Gender": "性别",
		"Parent Name": "家长姓名",
		"Home Phone": "家庭电话",
		"Cell Phone": "手机",
		"Cell Phone 2": "手机 2",
		"Pick up Person": "学生接人",
		"Address": "住址",
		"State": "州",
		"City": "城市",
		"Zipcode": "邮政编码",
		"Weekday/Weekend": "平日/周末",
		"Tuition Paid Day": "支付学费日期",
		"Payment Method": "付款方式",
		"Tuition Pay Amount": "总学费金额",
		"E-mail": "电子邮件",
		"Service Type": "课程级别",
		"Classes Awarded": "学生课程总数",
		"Classes Remaining": "剩下的课程",
		"Date": "日期",
		"Time": "Time",
		"Check-In Time": "到达时间",
		"Check-Out Time": "离开时间",
		"Start Time": "工作开始",
		"Class Time": "上课时间",
		"How did you hear about the school?": "你是怎么找到我们学校?",
		"Notes": "笔记",
		"No student": "找不到的学生 ！ 键入正确的名称或与系统管理员联系。 ",
		"Confirm Teacher Addition": "你确定你想这位老师向数据库中添加?",
		"Confirm Overwrite Teacher": "一个老师用相同的条码。如果想添加这个老师,你要覆盖旧的老师 ",
		"Teacher has been added to the database": "教师已被添加到数据库中",
		"Confirm Check-in Teacher": "入住这个老师? ",
		"Check out prompt": "签出这个教师?",
		"No classes": "这名学生没有课程",
		"Con print": "你想做报告吗？",
		"Overwrite Checkout": "改写签出",
		"Overwrite Check-In": "改写入住",
		"No Check-in today": "Teacher has not checked-in today",
		"Confirm late check-in": "Do you want to count this Check-In as 9:15AM?",
		"ok": "    确认    ",
		"yes": "    确认    ",
		"no": "    拒绝    ",
		"changelanguage": "Switch to English",
		"changelanguage_alt": "E",
		"awardclass": "奖类",
		"awardoneclass": "添加一课 (+1)",
		"awardaddclass": "奖其他类",
		"browse": "浏览",
		"browsephoto": "浏览照片",
		"addstudent": "新增学生资料",
		"Add Students": "新增教师", #students* for buttons
		"Scan Students": "登錄教师",
		"Scan Out Teacher": "註銷教师",
		"Save": "保存",
		"Student Database": "老师资料库",
		"Tools": "数据库管理",
		"Back to Main Menu": "返回主界面",
		"Exit": "关闭软件",
		"Next": "下一次",
		"Back": "返回",
		"Search": "搜索老师",
		"Search By": "搜索方式",
		"cinstudent": "入住教师",
		"savestudent": "储存老师数据库",
		"Database succesfully updated!": "数据库成功更新 ！ ",
		"File could not be imported": "不能导入文件 ",
		"Cancel": "取消",
		"Please choose a file": "请选择一个文件",
		"impdb": "导入数据库",
		"expdb": "数据报告",
		"impxls": "输入文档",
		"impt": "输入时间文档",
		"imptxls": "输入时间文档",
		"expxls": "数据报告",
		"curfile": "当前数据库文件",
		"choosedb": "选择数据库",
		"": "",
		"Classes remaining for this student": "学生剩余的课程",
		"spec": "",
		"gold60": "黄金 (+60)",
		"basic15": "基本 (+15)",
		"Return to Main Window": "返回主窗口而不保存",
		"Scan": "Scan",
		"Manual": "Manual",
		"Confirm Save Teacher Data": "确实要将此学生的信息保存到数据库吗？",
		"close": "关闭",
		"Amount Owed": "所欠学费数额",
		">> Next 30 >>": "下一个",
		"<< Previous 30 <<": "上一页",
		">>> Last Page >>>": "最后一页",
		"Import succesful": "导入成功 ",
		"Students imported: ": "导入的学生: ",
		"Attendance data imported: ": "导入考勤: ",
		"Student information": "教师信息",
		"Address information": "地址",
		"Contact information": "联络",
		"Payment information": "付款资料",
		"Class time": "上课时间",
		"Renew classes": "添加课程",
		"Membership Expired": "会员已过期",
		"Number of classes": "添加课程",
		"Card Printed": "已打印卡",
		"Already Paid": "已支付学费",
		"Phone Number": "电话号码",
		"RYB Student Management" : "红黄蓝老师管理软件",
		"print report": "每日报告",
		"sdate": "Search Date",
		"Select Folder": "Select Folder",
		"filepath": "File Path",
		"salrep": "创造工资",
		"print to file": "创造工资",
		"today's date": "今天日期",
		"last payment": "上次支付",
		"dollar per hour": "时薪",
		"Hour": "Hour",
		"Minute": "Minute",
		"AM/PM": "AM/PM",
		"Print All": "Print All",
		"Confirm Time": "确认时间",
		"Confirm": "Confirm",
		"25s": " 25s",
		"50s": " 50s",
		"100s": " 100s",
		"set": "Set",
		"reset": "Reset",
		"resetcheckin": "重设提前到达次",
		"Confirm Reset": "Confirm Reset?",
		"Early Check-ins have been reset": "Early Check-ins have been reset",
		"Yes, use current time": "使用现在时间",
		"Yes, enter time": "输入工作起始时间",
		"Brooklyn": "布鲁克林学校",
		"Chinatown": "唐人街学校",
		"Elmhurst": "艾姆赫斯特学校",
		"Flushing": "法拉盛学校",
		"Choose School": "选择学校",
		"Print Successful": "工资做出",
		"Early Check-in": "提前到达次",
		"max hours": "总工作小时",
		"Choose PW File": "选择密数据库",
		"Create PW File": "Create PW File",
		"Create new Database": "创造新数据库",
		"Convert to Encrypted DB": "转换为加密数据库",
		"no_pw_set_pw": "Password must be reset. Please enter the old password followed by the new password",
		"Enter Password": "输入密码",
		"Reset DB Manager PW": "复位密码",
		"confirmed reset": "Password has been reset!",
		"wrong password try again": "You have entered the wrong password, try again!",
		"Choose Maker File": "选择工资据库",
		"Create new Markerfile": "创造工资据库",
		"Database Backup Successful": "创建数据库成功",
		"Student Information": "Teacher Information",
		"Attendance Table": "Sign-in Table",
		"Manual Entry": "登錄教师",
		"Save Attendance": "Save Attendance",
		"Check-in": "到达时间",
		"Check-out": "离开时间",
		"Check-in date": "Check-in date",
		"School": "School",
		"Invalid Date": "Invalid Date",
		"Return": "Return",
		"Teacher Print Successful": "教师报告成功",
		"Check-Out Cannot be earlier than Check-In": "不能签出在签入前",
		"No Check-In on that Date": "老师没有入住在这日期",
		"Cannot Check-In a future time": "不能登记未来时间",
		"Password File": "Password File",
		"Preview": "Preview",
		"Output File": "Output File",
		"Source Excel": "Source Excel",
		"Invalid File Type": "Invalid File Type",
		"Print Simple Report": "Print Simple Report"
		}
		
}